# vim: set ft=ansible:
- name: copy the environment .pem key
  become: true
  copy:
    src: "{{playbook_dir}}/workdir/{{env_authorized_key}}"
    dest: "/root/.ssh/{{env_authorized_key}}.pem"
    owner: root
    group: root
    mode: 0400

- name: Set authorized key from file
  authorized_key:
    user: "{{ansible_ssh_user}}"
    state: present
#    key: "{{ playbook_dir }}/workdir/{{env_authorized_key}}.pub"
    key: "{{ lookup('file', '{{ playbook_dir }}/workdir/{{env_authorized_key}}.pub') }}"

- name: Generate host .ssh/config Template
  become: no
  local_action: template src={{role_path}}/files/host_ssh_config.j2 dest={{playbook_dir}}/workdir/ssh-config-{{ env_type }}-{{ guid }}

- name: copy over host .ssh/config Template
  become: true
  copy:
    src: "{{playbook_dir}}/workdir/ssh-config-{{ env_type }}-{{ guid }}"
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: 0400
