ansible_ssh_extra_args: >
  -o User={{ ansible_ssh_user }}
  -o StrictHostKeyChecking=no
  -i ~/.ssh/{{ key_name }}.pem
  -o ProxyCommand="ssh -o StrictHostKeyChecking=no -i ~/.ssh/'{{ key_name }}'.pem -o User='{{ ansible_ssh_user }}' -W %h:%p {{provisioner_public_dns_chomped}}"
