---
# defaults file for openshift-quota
# Based on kevensen.oc-project-creator (Thanks KevenSen)
ocp_username: shacharb-redhat.com
pod_quota: 20
# Hard quota for the number of services allowed in a project
service_quota: 20
# Hard quota for the number of replication controllers allowed in a project
rc_quota: 20
# Hard quota for the number of secrets allowed in a project
secret_quota: 20
# Hard quota for the size of total allocated storage for a project
storage_quota: 50Gi
# The role applied to the user who will "own" the project
project_role: admin
project_annotation_selector: "openshift.io/requester={{ocp_username}}"
requests_memory: 8Gi
requests_cpu: 6
limits_cpu: 10
limits.memory: 20Gi
configmaps: 20
persistentvolumeclaims: 10
