#set ft=ansible
---
- name: Test ssh by setting motd
  hosts: bastion_hostname.external
  remote_user: root
  become: true
  tasks:
    - debug:
        msg: 'hello there'
    - copy:
        content: "I'm a little teapot."
        dest: /etc/motd

