#set ft=ansible
---
- name: 'Wait for ssh service on {{ bastion_hostname.external }}'
  hosts: localhost
  tasks:
    - wait_for:
        port: 22
        host: "{{ bastion_hostname.external }}"
        search_regex: OpenSSH
        delay: 30
- name: Test ssh by setting motd
  hosts: bastion_host
  remote_user: cloud-user
  become: true
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_secret_vars.yml"
  tasks:
    - copy:
        content: "Welcome to Bastion. We hope you enjoy your stay.\n"
        dest: /etc/motd
      register: motd_changed
      until: motd_changed | success
      retries: 3
      delay: 25
      ignore_errors: yes  
