#vim: set ft=ansible:
---
######################### Install Basic Packages
- name: install basic packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{common_packages}}"
  register: yumr
  until: yumr is succeeded
  retries: 10
  delay: 10
  any_errors_fatal: true
  tags:
    - install_common_packages

- name: restart dbus and dnsmasq - bugfix
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - dnsmasq
    - dbus
  tags:
    - install_common_packages

- name: Enable NetworkManager
  service:
    name: NetworkManager
    state: restarted
    enabled: yes
  tags:
    - install_common_packages



