---
# tasks file for openshift-quota
- name: Set project quotas
  oc:
    validate_certs: "{{ ocp_validate_certs }}"
    token: "{{ ocp_ansible_sa_token }}"
    port: "{{ ocp_port | default(8443) }}"
    host: "{{ ocp_host | default('localhost') }}"
    state: present
    inline:
      kind: clusterquota
      metadata:
        name: "clusterquota-{{ocp_username}}"
        project_annotation_selector: "openshift.io/requester={{ocp_username}}"
      spec:
        hard:
          pods: "{{ pod_quota }}"
          services: "{{ service_quota }}"
          replicationcontrollers: "{{ rc_quota }}"
          secrets: "{{ secret_quota }}"
          requests.storage: "{{ storage_quota }}"
          requests_memory: 8Gi
          requests_cpu: 6
          limits_cpu: 10
          limits.memory: 20Gi
          configmaps: 20
          persistentvolumeclaims: 10
