---
# tasks file for openshift-quota
- debug:
    var: item
  with_items:
    - "{{ocp_token}}"
    - "{{ocp_master_api}}"

- name: Create user quota
  oc:
    host: master.dev1.openshift.opentlc.com
    port: 443
    validate_certs: false
    state: present
    token: "{{ ocp_token }}"

    inline:
      kind: ClusterResourceQuota
      metadata:
        name: "clusterquota-{{ocp_username}}"
      spec:
        quota:
          hard:
            pods: "{{ pod_quota }}"
            services: "{{ service_quota }}"
            replicationcontrollers: "{{ rc_quota }}"
            secrets: "{{ secret_quota }}"
            requests.storage: "{{ storage_quota }}"
            requests.memory: 8Gi
            requests.cpu: 6
            limits.cpu: 10
            limits.memory: 20Gi
            configmaps: 20
            persistentvolumeclaims: 10
        selector:
          annotations:
            openshift.io/requester: "{{ocp_username}}"
