# vim: set ft=ansible:
---
- name: Cleanup Infrastructure
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - "env_vars.yml"
    - "env_secret_vars.yml"
  tasks:
    - name: Delete S3 bucket
      s3_bucket: 
        name: "{{ env_type }}-{{ guid }}"
        state: absent
        force: yes
        region: "{{ aws_region }}"
      tags:
        - remove_s3

    - name: Delete Cloudformation Stack
      cloudformation:
        stack_name: "{{ env_type }}-{{ guid }}"
        state: "absent"
        region: "{{ aws_region }}"
      tags:
        - remove_cf
