#vim: set ft=ansible:
---
- name: POST Software Playbook NONE
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - "./env_vars.yml"
    - "./env_secret_vars.yml"
  tasks:
    - debug:
        msg: "included software playbook for: none [dummy only]"

    - name: generate ansible hosts file
      template:
        src: "./files/hosts_template.j2"
        dest: "../../workdir/hosts-{{ env_type }}-{{ guid }}"
      tags:
        - copy_hosts_file
- name: Step 00xxxxx bastion preparation for deployment
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_bastion') | replace('-', '_') }}"
  gather_facts: False
  become: yes
  vars_files:
    - "./env_vars.yml"
    - "./env_secret_vars.yml"
    - "./ssh_vars.yml"
  tasks:
    - name: Copy over ansible hosts file
      copy:
        src: "../../workdir/hosts-{{ env_type }}-{{ guid }}"
        dest: /etc/ansible/hosts
  tags:
    - copy_hosts_file
- name: Configuring Nfs Host
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_nfs') | replace('-', '_') }}"
  become: yes
  vars_files:
    - "./env_vars.yml"
    - "./ssh_vars.yml"
  roles:
    -  { role: "../../roles/nfs", when: "{{ install_nfs }}" }
  tags:
    - nfs_tasks
