- name: Starting environment deployment
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - "./env_vars.yml"
    - "./env_secret_vars.yml"

  tasks:

    - name: figure out hosted zone id
      shell: "aws route53 list-hosted-zones-by-name --region={{aws_region}} --output=text | grep {{zone_internal_dns}} | awk '{print $3}' | awk -F'/' '{print $3}'"
      register: internal_zone_register
    - debug:
        var: internal_zone_register.stdout
    - set_fact:
        internal_zone_id: "{{internal_zone_register.stdout}}"
    - name: DELETE internal dns names
      shell: "aws route53 change-resource-record-sets --hosted-zone-id {{internal_zone_id}}  --change-batch file://../../workdir/internal_dns-{{ env_type }}-{{ guid }}_DELETE.json --region={{aws_region}}"
      ignore_errors: trues
      tags:
        - internal_dns_delete

    - name: Destroy cloudformation template
      cloudformation:
        stack_name: "{{project_tag}}"
        state: "absent"
        region: "{{aws_region}}"
        disable_rollback: false
        template: "../../workdir/ec2_cloud_template.{{ env_type }}.{{ guid }}.json"
        tags:
          Stack: "project {{env_type}}-{{ guid }}"
      tags: [ destroying, destroy_cf_deployment ]



## we need to add something to delete the env specific key.
