---

# - name: Step 001.1 Configure local machine for bastion ssh proxy
#   vars_files:
#     - "{{playbook_dir}}/configs/{{ env_type }}/env_vars.yml"
#     - "{{playbook_dir}}/configs/{{ env_type }}/env_secret_vars.yml"
#   tags:
#     - step001
#     - step001.1
#     - deloy_infrastructure
#     - configure_local_ssh_proxy

# - name: debug groups
#   debug:
#     var: "{{item}}"
#   with_items:
#     - "{{groups['tag_AnsibleGroup_bastions']}}"

- name: get bastion Hostname
  set_fact:
    bastion_host: "{{item}}"
  with_items:
    - "{{groups['tag_AnsibleGroup_bastions']}}"
  when: '"{{env_type}}-{{guid}}" in hostvars[item].{{cloud_provider}}_tag_Project'

- name: get bastion Hostname
  debug:
    var: bastion_host

- name: get nfs Hostname
  set_fact:
    nfs_host: "{{item}}"
  with_items:
    - "{{groups['tag_AnsibleGroup_support']}}"
  when: '"{{env_type}}-{{guid}}" in hostvars[item].{{cloud_provider}}_tag_Project'

- name: get nfs Hostname
  debug:
    var: nfs_host



#### TODO ec2 references needs to be converted to {{cloud_provider}}
- name: Added Bastion Proxy to local ~/.ssh/config file
  blockinfile:
    dest: ~/.ssh/config
    marker: "##### {mark} ADDED BASTION PROXY HOST {{hostvars[item]['ec2_public_dns_name']}} {{ env_type }}-{{ guid }} ######"
    content: |
        Host {{hostvars[item]['ec2_public_dns_name']}}
          Hostname {{hostvars[item]['ec2_public_dns_name']}}
          ForwardAgent yes
          IdentityFile ~/.ssh/{{key_name}}.pem
          IdentitiesOnly yes
          User ec2-user
          ControlMaster auto
          ControlPath /tmp/{{ env_type }}
          ControlPersist 5m
          ForwardAgent yes
          StrictHostKeyChecking no
  with_items:
      - "{{groups['tag_AnsibleGroup_bastions']}}"
  when: 'hostvars[item].ec2_tag_Project is defined and "{{env_type}}-{{guid}}" in hostvars[item].ec2_tag_Project'


- name: Add all hosts to local  ~/.ssh/config file
  blockinfile:
    dest: ~/.ssh/config
    marker: "##### {mark} ADDED Node Proxy Config   {{hostvars[item]['ec2_public_dns_name']}} {{ env_type }}-{{ guid }} ######"
    block: |
        Host {{hostvars[item]['ec2_private_dns_name']}}
          Hostname {{hostvars[item]['ec2_private_dns_name']}}
          User ec2-user
          IdentityFile ~/.ssh/{{key_name}}.pem
          ProxyCommand ssh {{hostvars[bastion_host]['ec2_public_dns_name']}} -W %h:%p
          ForwardAgent yes
          StrictHostKeyChecking no
  with_items:
    - "{{ groups['all'] }}"
  when: 'hostvars[item].ec2_tag_Project is defined and "{{env_type}}-{{guid}}" in hostvars[item].ec2_tag_Project and "bastion" not in hostvars[item].ec2_tag_Name'
