# Create blueprint from existing app
---
  - hosts: localhost
    tasks: 
     - local_action:
         module: ravello_app
         name: 'ansible-brett-demo-version1.1-app-v1.0'
#         app_name: 'brett-demo-version1.1'
#        state: 'stopped'
         blueprint_name: 'test-brett-bp-save'
         blueprint_description: 'Blueprint of app xyz'
         state: blueprint
